
export type Roles =
    'ADMIN' |
    'VIEW_DASHBOARD' |
    'LIST_ORDERS' |
    'CRUD_OWN_ORDERS' |
    'CRUD_ALL_ORDERS' |
    'CRUD_CLIENTS' |
    'CRUD_PRODUCTS' |
    'LIST_VOUCHERS' |
    'CRUD_VOUCHERS' |
    'VIEW_SHOPS_MOVEMENTS' |
    'CRUD_SHOPS_MOVEMENTS' |
    'CRUD_STOCKS_UNITS_MOVEMENTS' |
    'CRUD_USERS' |
    'CRUD_CATEGORIES' |
    'VIEW_SHOPS' |
    'CRUD_SHOPS' |
    'VIEW_WAREHOUSES' |
    'CRUD_WAREHOUSES' |
    'VIEW_TEMPLATES' |
    'CRUD_TEMPLATES' |
    'VIEW_PAYMENTS' |
    'VIEW_CONFIGURATION' 
;