
export const enum Roles {
    Admin = 'Admin',
    View_Dashboard = 'View_Dashboard',
    List_Orders = 'List_Orders',
    CRUD_Own_Orders = 'CRUD_Own_Orders',
    CRUD_All_Orders = 'CRUD_All_Orders',
    CRUD_Clients = 'CRUD_Clients',
    CRUD_Products = 'CRUD_Products',
    List_Vouchers = 'List_Vouchers',
    CRUD_Vouchers = 'CRUD_Vouchers',
    View_Shops_Movements = 'View_Shops_Movements',
    CRUD_Shops_Movements = 'CRUD_Shops_Movements',
    CRUD_Stocks_Units_Movements = 'CRUD_Stocks_Units_Movements',
    CRUD_Users = 'CRUD_Users',
    CRUD_Categories = 'CRUD_Categories',
    View_Shops = 'View_Shops',
    CRUD_Shops = 'CRUD_Shops',
    View_Warehouses = 'View_Warehouses',
    CRUD_Warehouses = 'CRUD_Warehouses',
    View_Templates = 'View_Templates',
    CRUD_Templates = 'CRUD_Templates',
    View_Payments = 'View_Payments',
    View_Configuration = 'View_Configuration',
}